import { Category, Seller } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'all', label: 'All Fields' },
  { id: 'web', label: 'Web Design' },
  { id: 'logo', label: 'Logo Design' },
  { id: 'seo', label: 'SEO & Growth' },
  { id: 'video', label: 'Video Editing' },
  { id: 'app', label: 'App Dev' },
  { id: 'content', label: 'Content Writing' },
  { id: 'social', label: 'Social Media' },
  { id: 'uiux', label: 'UI/UX Design' }
];

export const DEFAULT_SELLERS: Seller[] = [
  {
    id: "s1",
    name: "Arif Hasan",
    level: "level-2",
    cat: "web",
    price: 50,
    rating: "4.9",
    reviews: 487,
    delivery: "3 Days Delivery",
    response: "1 Hour Response",
    orders: "520+ Orders Done",
    title: "I will design a modern, responsive website for your business",
    desc: "Professional web designer with 5+ years experience in creating stunning, conversion-focused websites.",
    img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200",
    skills: ["WordPress", "React", "Figma", "Responsive"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s2",
    name: "Fatima Rahman",
    level: "level-top",
    cat: "logo",
    price: 35,
    rating: "5.0",
    reviews: 1203,
    delivery: "2 Days Delivery",
    response: "30 Min Response",
    orders: "1,350+ Orders Done",
    title: "I will create a stunning logo and full brand identity",
    desc: "Award-winning graphic designer specializing in brand identity, logo design, and visual storytelling.",
    img: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200",
    skills: ["Logo", "Branding", "Illustrator", "Photoshop"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s3",
    name: "Rakib Ahmed",
    level: "level-2",
    cat: "seo",
    price: 80,
    rating: "4.8",
    reviews: 312,
    delivery: "7 Days Delivery",
    response: "2 Hour Response",
    orders: "340+ Orders Done",
    title: "I will do SEO optimization to rank your website on Google",
    desc: "SEO expert with proven results. Helped 300+ businesses rank on Google's first page.",
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
    skills: ["On-page SEO", "Technical SEO", "Backlinks"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s4",
    name: "Nadia Islam",
    level: "level-top",
    cat: "video",
    price: 40,
    rating: "4.9",
    reviews: 678,
    delivery: "2 Days Delivery",
    response: "45 Min Response",
    orders: "720+ Orders Done",
    title: "I will edit your video professionally for YouTube & social media",
    desc: "Creative video editor specializing in YouTube content, social media reels, and cinematic storytelling.",
    img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200",
    skills: ["Premiere Pro", "After Effects", "Motion Graphics"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s5",
    name: "Tariqul Bashar",
    level: "level-2",
    cat: "app",
    price: 120,
    rating: "5.0",
    reviews: 145,
    delivery: "14 Days Delivery",
    response: "1 Hour Response",
    orders: "150+ Orders Done",
    title: "I will build premium iOS and Android apps with Flutter",
    desc: "Senior mobile application architect with robust proficiency in cross-platform mobile ecosystem.",
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200",
    skills: ["Flutter", "Dart", "Firebase", "API Integration"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s6",
    name: "Sumi Akter",
    level: "level-top",
    cat: "content",
    price: 25,
    rating: "4.9",
    reviews: 432,
    delivery: "2 Days Delivery",
    response: "1 Hour Response",
    orders: "460+ Orders Done",
    title: "I will write SEO optimized content and blog posts for you",
    desc: "Expert content writer focused on high ranking articles, blogs, copywriting, brand voice research.",
    img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200",
    skills: ["Copywriting", "SEO Writing", "Blog Posts", "Editing"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s7",
    name: "Mahmudul Hasan",
    level: "level-2",
    cat: "social",
    price: 60,
    rating: "4.8",
    reviews: 198,
    delivery: "5 Days Delivery",
    response: "1 Hour Response",
    orders: "210+ Orders Done",
    title: "I will manage your corporate social media marketing campaigns",
    desc: "Digital marketer certified in Facebook, Instagram, LinkedIn campaigns and organic branding strategies.",
    img: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200",
    skills: ["Meta Ads", "Instagram Growth", "Content Calendar", "Analytics"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s8",
    name: "Tabassum Meem",
    level: "level-top",
    cat: "uiux",
    price: 75,
    rating: "5.0",
    reviews: 289,
    delivery: "5 Days Delivery",
    response: "45 Min Response",
    orders: "310+ Orders Done",
    title: "I will design gorgeous UI/UX for your mobile application or website",
    desc: "Stellar visual designer constructing user centered mockups, high-fidelity wireframes, interactive dynamic prototypes.",
    img: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200",
    skills: ["Figma UI", "Mobile UX", "Wireframes", "Design Systems"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s9",
    name: "Sajid Chowdhury",
    level: "level-2",
    cat: "web",
    price: 95,
    rating: "4.9",
    reviews: 167,
    delivery: "5 Days Delivery",
    response: "2 Hour Response",
    orders: "180+ Orders Done",
    title: "I will develop custom React and NextJS applications for you",
    desc: "Front-end engineer building high performance web applications with modern modular architectures.",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200",
    skills: ["ReactJS", "NextJS", "TailwindCSS", "TypeScript"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s10",
    name: "Jannatul Firdaus",
    level: "level-top",
    cat: "logo",
    price: 45,
    rating: "5.0",
    reviews: 843,
    delivery: "3 Days Delivery",
    response: "1 Hour Response",
    orders: "900+ Orders Done",
    title: "I will design minimalist custom vector logo concepts for brands",
    desc: "Clean geometry & typography focused logo artist providing multiple initial iterations and lifetime support.",
    img: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=200",
    skills: ["Minimal Logo", "Vector Graphics", "Brand Style Guide"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s11",
    name: "Imran Ahmed",
    level: "level-2",
    cat: "seo",
    price: 110,
    rating: "4.7",
    reviews: 142,
    delivery: "10 Days Delivery",
    response: "3 Hour Response",
    orders: "160+ Orders Done",
    title: "I will do detailed keyword research and competitor analysis",
    desc: "SEO Auditor extracting profitable search intents to guide content maps and link-building campaigns.",
    img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200",
    skills: ["Ahrefs", "Semrush", "Keyword Mapping", "Competitor Audit"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s12",
    name: "Priya Das",
    level: "level-top",
    cat: "video",
    price: 85,
    rating: "5.0",
    reviews: 310,
    delivery: "4 Days Delivery",
    response: "1 Hour Response",
    orders: "340+ Orders Done",
    title: "I will edit high engaging cinematic ads and promotional videos",
    desc: "Visual media editing specialist generating premium commercials with sound design and color grading.",
    img: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=200",
    skills: ["DaVinci Resolve", "Color Grading", "Cinematic Ads", "Sound SFX"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s13",
    name: "Rakibul Hasan",
    level: "level-2",
    cat: "app",
    price: 150,
    rating: "4.9",
    reviews: 88,
    delivery: "12 Days Delivery",
    response: "1 Hour Response",
    orders: "95+ Orders Done",
    title: "I will develop robust backend server APIs with Node and Express",
    desc: "Full-stack developer architecting database integrations and highly secured web microservices.",
    img: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=200",
    skills: ["NodeJS", "ExpressJS", "MongoDB", "PostgreSQL"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s14",
    name: "Nusrat Jahan",
    level: "level-top",
    cat: "social",
    price: 55,
    rating: "5.0",
    reviews: 215,
    delivery: "3 Days Delivery",
    response: "30 Min Response",
    orders: "240+ Orders Done",
    title: "I will write highly converting magnetic sales copy for social media",
    desc: "Digital copywriting specialist crafting posts that convert viewers into loyal premium clients.",
    img: "https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&q=80&w=200",
    skills: ["Social Copy", "Ad Copywriter", "Sales Hooks", "Branding"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  },
  {
    id: "s15",
    name: "Zahid Iqbal",
    level: "level-2",
    cat: "uiux",
    price: 50,
    rating: "4.8",
    reviews: 110,
    delivery: "4 Days Delivery",
    response: "2 Hour Response",
    orders: "130+ Orders Done",
    title: "I will create landing page UI UX designs ready for conversion",
    desc: "Interactive visual designer building desktop and mobile user experience pathways.",
    img: "https://images.unsplash.com/photo-1542206395-9feb3edaa68d?auto=format&fit=crop&q=80&w=200",
    skills: ["Landing Page", "UX Research", "UI Wireframes", "Figma"],
    link: "https://www.fiverr.com/?utm_source=freelancerhub"
  }
];
